version: '3'

services:
  backend:
    build: ./backend
    command: python api_project/manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - backend
